### PR TITLE
Added podspec

### PR DESCRIPTION
**Pull request by markmadlangbayan**

### CODE REVIEW

**Comment by erikpoort** [comment]
Please explain why you would like this to be a pod?
Also, the spec references your fork :)

**Comment by markmadlangbayan** [comment]
Hi @erikpoort, I don't like cocoapod pods myself; prefer carthage.  Pod for me is just an ongoing maintenance burden.  Unfortunately, because of dependency issues with a few third party libraries we were forced to use cocoapod.  Any react-native libraries with native code that depends on core React must be also be installed through Cocoapod.  If not, it won't compile, so many "can't find RCT*.h module errors.  I believe, this is a known issue with that RN is trying to solve.  In RN 0.60.x, it got better and they also defaulted react-native init's to pods.  I also think there's an ongoing push on RN 0.61.x rc to make cocoapod behave better.

I'm not too familiar with with "spec references" of my fork.  What does it mean?

Hope that helps,
-Mark

**Comment by erikpoort** [comment]
I am not really doing any RN development anymore, could you verify if it works?
Assuming I don't need to push this to the pods repo and this will be installed as a development pod.

**Comment by markmadlangbayan** [comment]
Thanks @erikpoort, it works.  For now, I just specify this in my `package.json`:
`"react-native-wallet": "erikpoort/react-native-wallet#250a864",`

You may eventually need to publish it to npmjs so that users can just specify `npm install ....`.

**Pull request merged**
